"""
Export cittaai.com's service catalogue (crawled by backend/scripts/sync_live_site.py) into
src/data/services.js, so the service pages show the live site's own copy, verbatim.

Usage (from frontend/): python scripts/export_services.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARRAYS = ROOT.parent / "backend" / "data" / "site_crawl" / "arrays.json"
OUT = ROOT / "src" / "data" / "services.js"

# Route slug on this site -> service id on cittaai.com, plus the per-page accent and 3D scene
ROUTES = {
    "data-engineering": ("data-engineering", "sky", "pipeline"),
    "enterprise-ai": ("enterprise-and-agentic-ai", "brand", "agents"),
    "ai-strategy": ("ai-strategy-and-advisory", "saffron", "roadmap"),
    "martech-360": ("ai-powered-martech", "coral", "funnel"),
}


def clean(value):
    """Drop the site's null icon/image fields and empty values."""
    if isinstance(value, dict):
        return {k: clean(v) for k, v in value.items() if k not in ("icon", "image") and v not in (None, "", [])}
    if isinstance(value, list):
        return [clean(v) for v in value]
    return value


def main():
    arrays = json.loads(ARRAYS.read_text(encoding="utf-8"))
    unwrap = lambda a: a["items"] if isinstance(a, dict) else a
    catalogue = {s["id"]: s for s in unwrap(arrays[0])}
    summaries = {s["title"]: s for s in unwrap(arrays[2])}
    services = []
    for slug, (site_id, accent, scene) in ROUTES.items():
        svc = catalogue[site_id]
        summary = next((s for t, s in summaries.items() if t.replace("360° ", "").startswith(svc["title"].split(" ")[0])), {})
        services.append({
            "slug": slug,
            "siteId": site_id,
            "title": summary.get("title", svc["title"]),
            "subtitle": summary.get("subtitle", ""),
            "description": summary.get("description", ""),
            "accent": accent,
            "scene": scene,
            "items": clean(svc["items"]),
        })
    body = json.dumps(services, ensure_ascii=False, indent=2)
    OUT.write_text(
        "// Generated by scripts/export_services.py from the live cittaai.com content. Do not edit by hand.\n"
        f"export const SERVICES = {body};\n\n"
        "export const SERVICE_BY_SLUG = Object.fromEntries(SERVICES.map((s) => [s.slug, s]));\n",
        encoding="utf-8",
    )
    print(f"{len(services)} services, {sum(len(s['items']) for s in services)} sub-services -> {OUT}")


if __name__ == "__main__":
    main()
